import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

const originalHome = process.env.OPENUNUM_HOME;
const testHome = fs.mkdtempSync(path.join(os.tmpdir(), 'openunum-skill-unify-'));

try {
  process.env.OPENUNUM_HOME = testHome;

  const { SkillManager } = await import('../src/skills/manager.mjs');
  const { AutoImprovementEngine } = await import('../src/core/auto-improve.mjs');
  const { SkillLearner } = await import('../src/core/skill-learner.mjs');
  const { defaultConfig } = await import('../src/config.mjs');

  const fakeMemory = {
    retrieveStrategyHints() {
      return [
        { strategy: 'Tool Driven Execution', success: true, evidence: 'completed_with_proof step=2' },
        { strategy: 'Tool Driven Execution', success: true, evidence: 'completed_with_proof step=4' },
        { strategy: 'Patch And Verify', success: true, evidence: 'completed_with_proof step=3' }
      ];
    },
    listSessions() {
      return [
        { sessionId: 's1', title: 'tool driven execution', preview: 'patch and verify workflow' },
        { sessionId: 's2', title: 'runtime validation', preview: 'tool driven execution with shell run' }
      ];
    },
    getRecentToolRuns(sessionId) {
      if (sessionId === 's1') {
        return [
          { ok: true, toolName: 'file_read' },
          { ok: true, toolName: 'file_patch' },
          { ok: true, toolName: 'shell_run' }
        ];
      }
      return [
        { ok: true, toolName: 'file_read' },
        { ok: true, toolName: 'file_patch' }
      ];
    },
    recordStrategyOutcome() {
      return { ok: true };
    }
  };

  const manager = new SkillManager();
  const autoImprove = new AutoImprovementEngine({
    memory: fakeMemory,
    config: defaultConfig(),
    agent: null
  });

  const generated = await autoImprove.generateSkillsFromSuccess();
  assert.equal(generated.length > 0, true);
  const listedAfterGenerate = manager.listSkills();
  assert.equal(listedAfterGenerate.length > 0, true);

  const generatedName = listedAfterGenerate[0].name;
  const generatedExec = await manager.executeSkill(generatedName, { probe: true });
  assert.equal(generatedExec.ok, true);
  assert.equal(generatedExec.name, generatedName);

  const learner = new SkillLearner({ memoryStore: fakeMemory });
  const learned = await learner.learnFromRecentMissions();
  assert.equal(learned.length > 0, true);

  const listedAfterLearn = manager.listSkills();
  assert.equal(listedAfterLearn.some((row) => row.autoGenerated === true), true);
  const learnedName = listedAfterLearn.find((row) => row.source === 'auto-learned')?.name;
  assert.equal(Boolean(learnedName), true);
  const learnedExec = await manager.executeSkill(learnedName, { dryRun: true });
  assert.equal(learnedExec.ok, true);
  assert.equal(learnedExec.result?.learned || learnedExec.result?.pattern != null, true);

  console.log('phase16.skill-unification.e2e: ok');
} finally {
  if (originalHome == null) delete process.env.OPENUNUM_HOME;
  else process.env.OPENUNUM_HOME = originalHome;
  fs.rmSync(testHome, { recursive: true, force: true });
}
