import fs from 'node:fs';
import path from 'node:path';
import { getHomeDir, ensureHome } from '../config.mjs';

export function loadSkills() {
  ensureHome();
  const skillsDir = path.join(getHomeDir(), 'skills');
  const manifestPath = path.join(skillsDir, 'manifest.json');
  const entries = fs.existsSync(skillsDir) ? fs.readdirSync(skillsDir, { withFileTypes: true }) : [];
  const skills = new Map();

  if (fs.existsSync(manifestPath)) {
    try {
      const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
      const rows = Array.isArray(manifest?.skills) ? manifest.skills : [];
      for (const row of rows) {
        const name = String(row?.name || '').trim();
        const filePath = String(row?.filePath || '').trim();
        if (!name || !filePath || !fs.existsSync(filePath)) continue;
        const code = fs.readFileSync(filePath, 'utf8');
        const meta = [
          `name=${name}`,
          `source=${row?.source || 'unknown'}`,
          `approved=${Boolean(row?.approved)}`,
          `verdict=${row?.verdict || 'pending_review'}`,
          `autoGenerated=${Boolean(row?.autoGenerated)}`
        ].join(' ');
        skills.set(name, {
          name,
          content: `Managed skill (${meta})\n\n${code.slice(0, 4000)}`
        });
      }
    } catch {
      // keep compatibility fallback below
    }
  }

  for (const e of entries) {
    if (!e.isDirectory()) continue;
    const skillPath = path.join(skillsDir, e.name, 'SKILL.md');
    if (!fs.existsSync(skillPath)) continue;
    if (!skills.has(e.name)) {
      skills.set(e.name, { name: e.name, content: fs.readFileSync(skillPath, 'utf8') });
    }
  }
  return [...skills.values()];
}
