import fs from 'node:fs';
import path from 'node:path';
import { getHomeDir, ensureHome } from '../config.mjs';

export function loadSkills() {
  ensureHome();
  const skillsDir = path.join(getHomeDir(), 'skills');
  const manifestPath = path.join(skillsDir, 'manifest.json');
  const entries = fs.existsSync(skillsDir) ? fs.readdirSync(skillsDir, { withFileTypes: true }) : [];
  const skills = new Map();

  if (fs.existsSync(manifestPath)) {
    try {
      const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
      const rows = Array.isArray(manifest?.skills) ? manifest.skills : [];
      for (const row of rows) {
        const name = String(row?.name || '').trim();
        const rawFilePath = String(row?.filePath || '').trim();
        if (!name || !rawFilePath || !fs.existsSync(rawFilePath)) continue;
        let skillPath = rawFilePath;
        if (fs.statSync(rawFilePath).isDirectory()) {
          const candidate = path.join(rawFilePath, 'SKILL.md');
          if (fs.existsSync(candidate) && fs.statSync(candidate).isFile()) {
            skillPath = candidate;
          } else {
            continue;
          }
        }
        const code = fs.readFileSync(skillPath, 'utf8');
        const meta = [
          `name=${name}`,
          `source=${row?.source || 'unknown'}`,
          `approved=${Boolean(row?.approved)}`,
          `verdict=${row?.verdict || 'pending_review'}`,
          `autoGenerated=${Boolean(row?.autoGenerated)}`
        ].join(' ');
        skills.set(name, {
          name,
          source: row?.source || 'managed',
          approved: row?.approved === true,
          verdict: row?.verdict || 'pending_review',
          usageCount: Number(row?.usageCount || 0),
          lastUsedAt: row?.lastUsedAt || null,
          installedAt: row?.installedAt || null,
          content: `Managed skill (${meta})\n\n${code.slice(0, 4000)}`
        });
      }
    } catch {
      // keep compatibility fallback below
    }
  }

  for (const e of entries) {
    if (!e.isDirectory()) continue;
    const skillPath = path.join(skillsDir, e.name, 'SKILL.md');
    if (!fs.existsSync(skillPath)) continue;
    if (!skills.has(e.name)) {
      skills.set(e.name, {
        name: e.name,
        source: 'filesystem',
        approved: null,
        verdict: 'n/a',
        usageCount: 0,
        lastUsedAt: null,
        installedAt: null,
        content: fs.readFileSync(skillPath, 'utf8')
      });
    }
  }
  return [...skills.values()];
}
