import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { getHomeDir, ensureHome } from '../config.mjs';

const MANIFEST_VERSION = 1;

function nowIso() {
  return new Date().toISOString();
}

function normalizeSkillName(input) {
  return String(input || '')
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9._-]/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
}

function defaultSkillModuleSource({
  name,
  description = '',
  pattern = '',
  toolSequence = [],
  evidence = ''
}) {
  const lines = [
    '// Auto-generated skill module.',
    `export const metadata = ${JSON.stringify({
      name,
      description,
      pattern,
      toolSequence,
      evidence,
      generatedAt: nowIso()
    }, null, 2)};`,
    '',
    'export async function execute(args = {}) {',
    '  const providedSteps = Array.isArray(args?.steps) ? args.steps : [];',
    '  const defaultSteps = Array.isArray(metadata.toolSequence) ? metadata.toolSequence : [];',
    '  const steps = providedSteps.length ? providedSteps : defaultSteps;',
    '  return {',
    '    ok: true,',
    '    skill: metadata.name,',
    '    description: metadata.description,',
    '    pattern: metadata.pattern || "",',
    '    steps,',
    '    evidence: metadata.evidence || "",',
    '    receivedArgs: args',
    '  };',
    '}',
    '',
    'export default execute;',
    ''
  ];
  return lines.join('\n');
}

function analyzeCode(content) {
  const checks = [
    { code: 'eval', severity: 'critical', pattern: /\beval\s*\(/ },
    { code: 'function_constructor', severity: 'critical', pattern: /\bnew\s+Function\s*\(/ },
    { code: 'child_process', severity: 'high', pattern: /\bnode:child_process\b|\bchild_process\b/ },
    { code: 'fs_write', severity: 'medium', pattern: /\bwriteFile|appendFile|rmSync|unlinkSync|chmod|chown\b/ },
    { code: 'network_access', severity: 'medium', pattern: /\bfetch\s*\(|\bhttps?:\/\//i },
    { code: 'env_access', severity: 'medium', pattern: /\bprocess\.env\b/ }
  ];
  const findings = checks
    .filter((c) => c.pattern.test(content))
    .map((c) => ({ code: c.code, severity: c.severity }));
  const hasCritical = findings.some((f) => f.severity === 'critical');
  const hasHigh = findings.some((f) => f.severity === 'high');
  const verdict = hasCritical ? 'rejected' : hasHigh ? 'pending_review' : findings.length ? 'reviewed' : 'safe';
  return { verdict, findings };
}

export class SkillManager {
  constructor() {
    ensureHome();
    this.homeDir = getHomeDir();
    this.skillsDir = path.join(this.homeDir, 'skills');
    this.customDir = path.join(this.skillsDir, 'custom');
    this.manifestPath = path.join(this.skillsDir, 'manifest.json');
    this.init();
  }

  init() {
    if (!fs.existsSync(this.customDir)) fs.mkdirSync(this.customDir, { recursive: true });
    if (!fs.existsSync(this.manifestPath)) {
      const initial = { version: MANIFEST_VERSION, updatedAt: nowIso(), skills: [] };
      fs.writeFileSync(this.manifestPath, JSON.stringify(initial, null, 2), 'utf8');
    }
  }

  loadManifest() {
    const raw = fs.readFileSync(this.manifestPath, 'utf8');
    const parsed = JSON.parse(raw);
    if (!Array.isArray(parsed.skills)) parsed.skills = [];
    return parsed;
  }

  saveManifest(manifest) {
    manifest.updatedAt = nowIso();
    fs.writeFileSync(this.manifestPath, JSON.stringify(manifest, null, 2), 'utf8');
  }

  listSkills() {
    const manifest = this.loadManifest();
    return manifest.skills.map((s) => ({
      name: s.name,
      source: s.source || 'unknown',
      autoGenerated: Boolean(s.autoGenerated),
      approved: Boolean(s.approved),
      verdict: s.verdict || 'pending_review',
      installedAt: s.installedAt,
      lastUsedAt: s.lastUsedAt || null,
      usageCount: Number(s.usageCount || 0),
      findings: s.findings || [],
      isBundle: Boolean(s.isBundle)
    }));
  }

  async loadSkillBundle(name) {
    const normalized = normalizeSkillName(name);
    const manifest = this.loadManifest();
    const skill = manifest.skills.find((s) => s.name === normalized);
    if (!skill) throw new Error('skill_not_found');

    if (!skill.isBundle) {
      // Legacy single-file support: just return content and metadata
      const content = fs.readFileSync(skill.filePath, 'utf8');
      return {
        name: skill.name,
        isBundle: false,
        files: { [skill.fileName]: content }
      };
    }

    // New bundle support: load all files in the skill directory
    const bundleDir = skill.filePath; // For bundles, filePath points to the directory
    if (!fs.existsSync(bundleDir) || !fs.statSync(bundleDir).isDirectory()) {
      throw new Error('skill_bundle_directory_missing');
    }

    const files = {};
    const entries = fs.readdirSync(bundleDir);
    for (const entry of entries) {
      const fullPath = path.join(bundleDir, entry);
      if (fs.statSync(fullPath).isFile()) {
        files[entry] = fs.readFileSync(fullPath, 'utf8');
      }
    }

    return {
      name: skill.name,
      isBundle: true,
      path: bundleDir,
      files
    };
  }

  async installSkill({ source, name, content }) {
    // ... existing installSkill implementation (kept for single-file compat)
    let code = String(content || '');
    if (!code && source) {
      if (String(source).startsWith('http://') || String(source).startsWith('https://')) {
        const res = await fetch(source);
        if (!res.ok) throw new Error(`skill_download_failed:${res.status}`);
        code = await res.text();
      } else {
        const srcPath = path.resolve(process.cwd(), source);
        code = fs.readFileSync(srcPath, 'utf8');
      }
    }
    if (!code.trim()) throw new Error('skill_content_required');

    const normalized = normalizeSkillName(name || source || `skill-${Date.now()}`);
    if (!normalized) throw new Error('invalid_skill_name');
    const fileName = normalized.endsWith('.mjs') ? normalized : `${normalized}.mjs`;
    const filePath = path.join(this.customDir, fileName);
    if (fs.existsSync(filePath)) throw new Error('skill_exists');

    const report = analyzeCode(code);
    fs.writeFileSync(filePath, code, 'utf8');

    const manifest = this.loadManifest();
    manifest.skills.push({
      name: normalized,
      fileName,
      filePath,
      source: source || 'inline',
      installedAt: nowIso(),
      approved: report.verdict === 'safe',
      verdict: report.verdict,
      findings: report.findings,
      usageCount: 0
    });
    this.saveManifest(manifest);

    return {
      ok: true,
      name: normalized,
      filePath,
      verdict: report.verdict,
      findings: report.findings,
      requiresApproval: report.verdict !== 'safe'
    };
  }

  upsertGeneratedSkill({
    name,
    description = '',
    pattern = '',
    toolSequence = [],
    evidence = '',
    content = '',
    source = 'generated'
  }) {
    const normalized = normalizeSkillName(name || `generated-skill-${Date.now()}`);
    if (!normalized) throw new Error('invalid_skill_name');
    const fileName = normalized.endsWith('.mjs') ? normalized : `${normalized}.mjs`;
    const filePath = path.join(this.customDir, fileName);
    const moduleSource = String(content || '').trim() || defaultSkillModuleSource({
      name: normalized,
      description,
      pattern,
      toolSequence,
      evidence
    });
    const report = analyzeCode(moduleSource);
    fs.writeFileSync(filePath, moduleSource, 'utf8');

    const manifest = this.loadManifest();
    const existing = manifest.skills.find((s) => s.name === normalized);
    const nextRow = {
      name: normalized,
      fileName,
      filePath,
      source,
      installedAt: existing?.installedAt || nowIso(),
      updatedAt: nowIso(),
      approved: report.verdict !== 'rejected',
      verdict: report.verdict,
      findings: report.findings,
      usageCount: Number(existing?.usageCount || 0),
      autoGenerated: true,
      pattern,
      description,
      evidence
    };
    if (existing) {
      Object.assign(existing, nextRow, {
        lastUsedAt: existing.lastUsedAt || null
      });
    } else {
      manifest.skills.push({
        ...nextRow,
        lastUsedAt: null
      });
    }
    this.saveManifest(manifest);

    return {
      ok: true,
      upserted: true,
      name: normalized,
      filePath,
      verdict: report.verdict,
      findings: report.findings
    };
  }

  reviewSkill(name) {
    const normalized = normalizeSkillName(name);
    const manifest = this.loadManifest();
    const skill = manifest.skills.find((s) => s.name === normalized);
    if (!skill) throw new Error('skill_not_found');
    const code = fs.readFileSync(skill.filePath, 'utf8');
    const report = analyzeCode(code);
    skill.verdict = report.verdict;
    skill.findings = report.findings;
    if (report.verdict === 'rejected') skill.approved = false;
    this.saveManifest(manifest);
    return { ok: true, name: skill.name, verdict: skill.verdict, findings: skill.findings };
  }

  approveSkill(name) {
    const normalized = normalizeSkillName(name);
    const manifest = this.loadManifest();
    const skill = manifest.skills.find((s) => s.name === normalized);
    if (!skill) throw new Error('skill_not_found');
    if (skill.verdict === 'rejected') throw new Error('skill_rejected_cannot_approve');
    skill.approved = true;
    skill.approvedAt = nowIso();
    this.saveManifest(manifest);
    return { ok: true, name: skill.name, approved: true };
  }

  async installSkillBundle({ name, files = {}, source = 'manual' }) {
    const normalized = normalizeSkillName(name || `bundle-${Date.now()}`);
    const bundleDir = path.join(this.customDir, normalized);
    if (fs.existsSync(bundleDir)) throw new Error('skill_exists');

    fs.mkdirSync(bundleDir, { recursive: true });
    for (const [fileName, content] of Object.entries(files)) {
      const filePath = path.join(bundleDir, fileName);
      fs.writeFileSync(filePath, String(content), 'utf8');
    }

    const manifest = this.loadManifest();
    manifest.skills.push({
      name: normalized,
      isBundle: true,
      filePath: bundleDir,
      source,
      installedAt: nowIso(),
      approved: true, // Bundles from factory/manual are trusted by default in this context
      verdict: 'safe',
      usageCount: 0
    });
    this.saveManifest(manifest);

    return { ok: true, name: normalized, path: bundleDir };
  }

  async executeSkill(name, args = {}) {
    const normalized = normalizeSkillName(name);
    const manifest = this.loadManifest();
    const skill = manifest.skills.find((s) => s.name === normalized);
    if (!skill) throw new Error('skill_not_found');
    if (!skill.approved && skill.verdict !== 'safe') throw new Error('skill_not_approved');

    let execPath = skill.filePath;
    if (skill.isBundle) {
      execPath = path.join(skill.filePath, 'execute.mjs');
      if (!fs.existsSync(execPath)) {
        throw new Error('skill_bundle_no_executable');
      }
    }

    const mod = await import(`${pathToFileURL(execPath).href}?t=${Date.now()}`);
    const fn = typeof mod.execute === 'function' ? mod.execute : (typeof mod.default === 'function' ? mod.default : null);
    if (!fn) throw new Error('invalid_skill_exports');
    const result = await fn(args);

    skill.usageCount = Number(skill.usageCount || 0) + 1;
    skill.lastUsedAt = nowIso();
    this.saveManifest(manifest);
    return { ok: true, name: skill.name, result };
  }

  uninstallSkill(name) {
    const normalized = normalizeSkillName(name);
    const manifest = this.loadManifest();
    const idx = manifest.skills.findIndex((s) => s.name === normalized);
    if (idx < 0) throw new Error('skill_not_found');
    const [skill] = manifest.skills.splice(idx, 1);
    
    if (skill?.filePath && fs.existsSync(skill.filePath)) {
      if (skill.isBundle && fs.statSync(skill.filePath).isDirectory()) {
        fs.rmSync(skill.filePath, { recursive: true, force: true });
      } else {
        fs.unlinkSync(skill.filePath);
      }
    }
    
    this.saveManifest(manifest);
    return { ok: true, name: normalized, removed: true };
  }
}
